curl http://localhost:8080/app

###
curl http://localhost:8080/admin/metrics

### 
POST http://localhost:8080/api/users HTTP/1.1
content-type: application/json

{
  "password": "04234",
  "email": "jeronimo@example.com"
}

### 
POST http://localhost:8080/api/login HTTP/1.1
content-type: application/json

{
  "email": "jeronimo@example.com",
  "password": "04234"
}


###
POST http://localhost:8080/admin/reset HTTP/1.1


Authorization: Bearer

###
POST http://localhost:8080/api/chirps HTTP/1.1
content-type: application/json
Authorization: Bearer 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiJmMDM1NmU3OS03YzkwLTQ4ZTMtYmMwYS1jOGEwMjc1ZDkxZDkiLCJleHAiOjE3NTkxMjAyOTAsImlhdCI6MTc1OTExNjY5MH0.PXS9LQzyvAgrgHHvnsOk0kW5m-FpeOwtMkm71_ZibVs

{
  "body": "jeronimo here"
}

###
GET http://localhost:8080/api/chirps HTTP/1.1

###
GET http://localhost:8080/api/chirps/f0356e79-7c90-48e3-bc0a-c8a0275d91d9 HTTP/1.1


###
POST http://localhost:8080/api/refresh HTTP/1.1
Authorization: Bearer ea2c1a321b7b6441532586c7b31d141531d037041c2ef7bac83f996030cff00a



###
POST http://localhost:8080/api/revoke HTTP/1.1
Authorization: Bearer ea2c1a321b7b6441532586c7b31d141531d037041c2ef7bac83f996030cff00a


###
PUT  http://localhost:8080/api/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiIxOTJmOTQ1MS0yMzc1LTQ2YmYtOGJlOC04NGVhNzA3OGJkODkiLCJleHAiOjE3NTkxNzQ4MzMsImlhdCI6MTc1OTE3MTIzM30.UC871Ut8c_juJEyjO-Ht0CbSVcUEq0-CPe3HYeQYQbw

{
  "email": "jeronimo-new@example.com",
  "password": "1129"
}



sqlc generate
goose postgres postgres://jeronimo:@localhost:5432/chirpy up
psql "postgres://jeronimo:@localhost:5432/chirpy"