curl http://localhost:8080/app

###
curl http://localhost:8080/admin/metrics

###
POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "body": "I had something interesting for breakfast"
}

###
POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "body": "I hear Mastodon is better than Chirpy. sharbert I need to migrate",
  "extra": "this should be ignored"
}

###
POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "body": "I really need a kerfuffle to go to bed sooner, Fornax !"
}

###
POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "body": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
}

### 
POST http://localhost:8080/api/users HTTP/1.1
content-type: application/json

{
  "password": "04234",
  "email": "lane@example.com"
}

### 
POST http://localhost:8080/api/login HTTP/1.1
content-type: application/json

{
  "password": "042e34",
  "email": "lane@example.com"
}



###
POST http://localhost:8080/admin/reset HTTP/1.1



###
POST http://localhost:8080/api/chirps HTTP/1.1
content-type: application/json

{
  "body": "Hello, world!",
  "user_id": "eea465fd-2dc8-4f54-9a74-1405afed4f92"
}

###
GET http://localhost:8080/api/chirps HTTP/1.1

###
GET http://localhost:8080/api/chirps/123e4567-e89b-12d3-a456-426614174059 HTTP/1.1






sqlc generate
goose postgres postgres://jeronimo:@localhost:5432/chirpy up
psql "postgres://jeronimo:@localhost:5432/chirpy"